# -*- coding: utf-8 -*-
"""lv1_min_rectangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-yWdve1HI3TgM0f4kBFnBonRxFVvdWJh
"""

sizes = [[60, 50], [30, 70], [60, 30], [80, 40]]

sizes = [sorted(size, reverse=True) for size in sizes]
print(sizes)

widths = [size[0] for size in sizes]
heights = [size[1] for size in sizes]
print(widths, heights)

print(max(widths), max(heights), max(widths)*max(heights))

