# -*- coding: utf-8 -*-
"""lv1_mbti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Twx7XabmzVH-k-Lu1Ln6xDXK9SIU2e-J
"""

survey = ["AN", "CF", "MJ", "RT", "NA"]
choices = [5, 3, 2, 7, 5]
answer = ''

from collections import defaultdict
indicator = [('R', 'T'), ('C', 'F'), ('J', 'M'), ('A', 'N')]
mbti = defaultdict(int) # mbti라는 dictionary가 비어있는 경우 0 값으로 셋팅해줌

print(indicator)
print(mbti)

for s, c in zip(survey, choices):
  print(s, c)
  if c < 4: # 앞의 유형+
    mbti[s[0]] += (4-c)
    print(s[0], mbti[s[0]])
  elif c > 4: #뒤의 유형+
    mbti[s[1]] += (c-4)
    print(s[1], mbti[s[1]])
  print()
print(mbti)

for i in indicator:
  if mbti[i[0]] >= mbti[i[1]]:
    answer += i[0]
  else:
    answer += i[1]
print(answer)